version: '3'
services:
  planet:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: planet/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - mongodb
    networks: 
      - production-network
  mongodb:
    image: mongo
    networks: 
      - production-network

networks: 
    production-network:
        driver: bridge